// Chapter 22: Fault Lines
// Source: dialogue_storymode

var chapter22Scene = createDialogueScene({
    id: "chapter_22",
    background: "rebel_safehouse",
    chapterTitle: "Chapter 22: \"Fault Lines\"",
    dialogue: [
        { speaker: "Narrator",       emotion: "neutral",    text: "This chapter has four pillars: Emotional aftermath. Locker room fracture. Public speech decision. Political recalibration. This is not explosive. It's heavy." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Scene change: Aftermath Silence (Rebellion Route — Rebecca Captured). Rebel Safehouse. Night." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Otto sitting alone. News reports replay footage of Rebecca being led away." },
        { speaker: "Reporter",       emotion: "neutral",    text: "The government claims evidence links her to organized resistance." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Otto stares at screen." },
        { speaker: "Rebel Leader",   emotion: "serious",    text: "They want you angry." },
        { speaker: "Otto",           emotion: "serious",    text: "They have me." },
        { speaker: "Leader",         emotion: "serious",    text: "That's what they need." },
        { speaker: "Otto",           emotion: "serious",    text: "No... what they need is fear." },
        { speaker: "Narrator",       emotion: "neutral",    text: "He stands." },
        { speaker: "Otto",           emotion: "serious",    text: "They won't get that." },
        { speaker: "Narrator",       emotion: "neutral",    text: "This is the first moment Otto becomes colder." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Scene change: Quiet Route (Love Shot). Hospital Room. Night. Love asleep. Bandaged shoulder or side. Otto sitting beside the bed. Her hand twitches. She wakes weakly." },
        { speaker: "Love",           emotion: "neutral",    text: "You okay?" },
        { speaker: "Narrator",       emotion: "neutral",    text: "Otto almost laughs." },
        { speaker: "Otto",           emotion: "neutral",    text: "I should be asking you that." },
        { speaker: "Narrator",       emotion: "neutral",    text: "She studies him." },
        { speaker: "Love",           emotion: "serious",    text: "Don't do something reckless." },
        { speaker: "Otto",           emotion: "serious",    text: "I didn't do anything. And this still happened." },
        { speaker: "Narrator",       emotion: "neutral",    text: "That line hits. She squeezes his hand." },
        { speaker: "Love",           emotion: "neutral",    text: "Then do something meaningful." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Scene change: Locker Room Fracture. Westward Locker Room. Day. Tension thick." },
        { speaker: "Teammate #1",    emotion: "serious",    text: "My family's scared because of this." },
        { speaker: "Teammate #2",    emotion: "neutral",    text: "We're athletes, not activists." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Silence. Coach Baker enters." },
        { speaker: "Coach Baker",    emotion: "serious",    text: "This team was built on unity." },
        { speaker: "Narrator",       emotion: "neutral",    text: "He looks at Otto." },
        { speaker: "Coach Baker",    emotion: "serious",    text: "But unity doesn't mean silence." },
        { speaker: "Another Player", emotion: "neutral",    text: "Or rebellion." },
        { speaker: "Coach Baker",    emotion: "serious",    text: "We have a Semi-Final in two days." },
        { speaker: "Coach Baker",    emotion: "serious",    text: "Figure yourselves out or else everything we worked for will be for nothing, and that's how they keep us poor." },
        { speaker: "Coach Baker",    emotion: "serious",    text: "Divided." },
        { speaker: "Narrator",       emotion: "neutral",    text: "He leaves. Otto stands in the middle of the room. No speech. Just tension." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Scene change: Public Speech Decision. Press conference announced. Entire nation watching. Otto steps to podium. Flashbulbs." },
        { speaker: "Reporter",       emotion: "neutral",    text: "Are you responsible for what happened?" },
        { speaker: "Reporter",       emotion: "neutral",    text: "Will you denounce the protests?" },
        { speaker: "Reporter",       emotion: "neutral",    text: "Will you condemn the government?" },
        { speaker: "Narrator",       emotion: "neutral",    text: "Silence. Otto chooses his tone.",
          choices: [{ text: "Direct condemnation", next: "ch22_condemn" }] },
        { speaker: "Otto",           emotion: "serious",    text: "You don't raid families to protect a country." },
        { speaker: "Otto",           emotion: "serious",    text: "You do that when you're afraid of it." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Room erupts." },
        { speaker: "Otto",           emotion: "serious",    text: "I stood beside leaders who promised safety. Safety failed." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Silence. Powerful but careful." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Scene change: Private Moment. She watches speech on TV." },
        { speaker: "Love",           emotion: "neutral",    text: "You chose." },
        { speaker: "Otto",           emotion: "neutral",    text: "Yeah." },
        { speaker: "Love",           emotion: "neutral",    text: "Was it the right one?" },
        { speaker: "Otto",           emotion: "neutral",    text: "I don't know yet." },
        { speaker: "Love",           emotion: "neutral",    text: "Can I get a kiss now?" },
        { speaker: "Narrator",       emotion: "neutral",    text: "They sit laughing." },
        { speaker: "Narrator",       emotion: "neutral",    text: "If Rebecca Captured: Otto visits prison. Rebecca behind glass." },
        { speaker: "Rebecca",        emotion: "neutral",    text: "You look different." },
        { speaker: "Otto",           emotion: "neutral",    text: "They made me." },
        { speaker: "Rebecca",        emotion: "neutral",    text: "Good. Fuck them." },
        { speaker: "Narrator",       emotion: "neutral",    text: "She smiles faintly." },
        { speaker: "Rebecca",        emotion: "serious",    text: "Just don't get power hungry." },
        { speaker: "Narrator",       emotion: "neutral",    text: "That line matters." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Scene change: Presidential War Room." },
        { speaker: "Vice President", emotion: "neutral",    text: "He escalated." },
        { speaker: "President",      emotion: "neutral",    text: "He committed." },
        { speaker: "Vice President", emotion: "neutral",    text: "To which side?" },
        { speaker: "President",      emotion: "serious",    text: "That's what makes him dangerous." },
        { speaker: "Narrator",       emotion: "neutral",    text: "President leans forward." },
        { speaker: "President",      emotion: "serious",    text: "Prepare the Semi-Final security operation." },
        { speaker: "Vice President", emotion: "neutral",    text: "You think he'll use it?" },
        { speaker: "President",      emotion: "serious",    text: "I hope he does." },
        { speaker: "Narrator",       emotion: "neutral",    text: "An unknown gunman shoots the vice president." },
        { speaker: "President",      emotion: "serious",    text: "Call an ambulance!!" },
        { speaker: "President",      emotion: "serious",    text: "Someone help!" },
        { speaker: "Royal Guard",    emotion: "serious",    text: "Mr. President!!" },
        { speaker: "Narrator",       emotion: "neutral",    text: "End of Chapter 22. The country is polarized. The team is divided. Otto has chosen a tone publicly. Now the Semi-Final becomes symbolic. Next: Chapter 23 — The Semi-Final." }
    ],
    next: null
});
