// Chapter 4 — "Beginner's Luck"
// Source: dialogue_storymode

var chapter4Scene = createDialogueScene({
    id: "chapter_4_scene",
    background: "locker_room",
    chapterTitle: "Chapter 4: Beginner's Luck",
    dialogue: [
        { speaker: "Narrator",    emotion: "neutral",    text: "Scene change: Locker Room After the Match. The locker room smells like sweat, disinfectant, and disbelief. Someone laughs too loudly. Someone else shouts. A towel gets thrown across the room." },
        { speaker: "Narrator",    emotion: "neutral",    text: "They won. Not pretty. Not dominant. But real. Westward wins — Opponent loses." },
        { speaker: "Narrator",    emotion: "neutral",    text: "Otto sits on the bench, still in his kit, pulse slowing. He didn't play much — late minutes — but he was on the field when the final whistle blew. That counts." },
        { speaker: "Captain",     emotion: "neutral",    text: "Hey. A win is a win." },
        { speaker: "Narrator",    emotion: "neutral",    text: "A few players nod. A few smile. No one celebrates like champions. Coach Baker walks in last. He doesn't smile." },
        { speaker: "Coach Baker", emotion: "serious",    text: "Good. You didn't embarrass yourselves." },
        { speaker: "Narrator",    emotion: "neutral",    text: "A couple of players chuckle." },
        { speaker: "Coach Baker", emotion: "serious",    text: "Don't confuse that with being good." },
        { speaker: "Narrator",    emotion: "neutral",    text: "Silence." },
        { speaker: "Coach Baker", emotion: "serious",    text: "Enjoy tonight. Tomorrow we train." },
        { speaker: "Narrator",    emotion: "neutral",    text: "He turns and leaves. Otto exhales." },
        { speaker: "Narrator",    emotion: "neutral",    text: "Scene change: Team Apartment / Common Room. Later that night. A small TV. Everyone crammed onto couches, chairs, the floor. Takeout containers stacked like trophies. The sports news comes on. Bright lights. Clean suits. Smiling anchors." },
        { speaker: "Anchor 1",    emotion: "neutral",    text: "Well, Westward pulled off an upset today." },
        { speaker: "Anchor 2",    emotion: "neutral",    text: "Let's be honest — pulled off is the key phrase." },
        { speaker: "Narrator",    emotion: "neutral",    text: "A graphic flashes: WESTWARD FC — WIN." },
        { speaker: "Anchor 3",    emotion: "neutral",    text: "They got lucky. Plain and simple." },
        { speaker: "Narrator",    emotion: "neutral",    text: "The room goes quiet." },
        { speaker: "Anchor 2",    emotion: "neutral",    text: "They faced a team that failed to capitalize early. That won't happen often." },
        { speaker: "Anchor 1",    emotion: "neutral",    text: "And let's talk about the coach. Baker's first season with this club was a disaster." },
        { speaker: "Narrator",    emotion: "neutral",    text: "Clips roll: losses from last year. Missed chances. Headlines." },
        { speaker: "Anchor 1",    emotion: "neutral",    text: "No identity. No depth. No results." },
        { speaker: "Narrator",    emotion: "neutral",    text: "Otto's jaw tightens." },
        { speaker: "Anchor 3",    emotion: "neutral",    text: "I don't see improvement. I see a team that maybe wins one or two games if the wind blows right." },
        { speaker: "Narrator",    emotion: "neutral",    text: "Laughter from the desk. A graphic pops up: PREDICTED TABLE — BOTTOM THREE. Westward's logo sits near the bottom." },
        { speaker: "Anchor 2",    emotion: "neutral",    text: "I have them finishing eighteenth." },
        { speaker: "Anchor 1",    emotion: "neutral",    text: "Nineteenth." },
        { speaker: "Anchor 3",    emotion: "neutral",    text: "Last." },
        { speaker: "Narrator",    emotion: "neutral",    text: "The screen freezes on Westward's badge." },
        { speaker: "Narrator",    emotion: "neutral",    text: "Scene change: Reaction. Someone throws an empty container at the wall." },
        { speaker: "Teammate",    emotion: "angry",      text: "Lucky?!" },
        { speaker: "Another",     emotion: "angry",      text: "They didn't even watch the match!" },
        { speaker: "Captain",     emotion: "serious",    text: "Mute it." },
        { speaker: "Narrator",    emotion: "neutral",    text: "The TV goes silent, but the damage is done. Otto stands up. His hands are shaking." },
        { speaker: "Otto",        emotion: "serious",    text: "They talk like we're already dead." },
        { speaker: "Narrator",    emotion: "neutral",    text: "No one argues." },
        { speaker: "Otto",        emotion: "serious",    text: "They don't know us." },
        { speaker: "Narrator",    emotion: "neutral",    text: "A beat." },
        { speaker: "Otto",        emotion: "serious",    text: "They don't know what it took just to get here." },
        { speaker: "Narrator",    emotion: "neutral",    text: "The captain looks at him." },
        { speaker: "Captain",     emotion: "determined", text: "They will." },
        { speaker: "Narrator",    emotion: "neutral",    text: "Otto nods, but the anger stays. It burns low. Controlled. The kind that lasts." },
        { speaker: "Narrator",    emotion: "neutral",    text: "Scene change: Late Night. Otto lies in bed, phone glowing. Sports comment thread: 'Beginner's luck.' 'Enjoy it while it lasts.' 'Westward won't survive the season.'" },
        { speaker: "Otto (inner voice)", emotion: "serious", text: "They're waiting for us to fail." },
        { speaker: "Narrator",    emotion: "neutral",    text: "He turns onto his side." },
        { speaker: "Otto (inner voice)", emotion: "determined", text: "Good." },
        { speaker: "Narrator",    emotion: "neutral",    text: "Outside, the city hums like it doesn't care who wins." },
        { speaker: "Narrator",    emotion: "neutral",    text: "Scene change: Next Morning. Training ground. Coach Baker watches them run. Harder than yesterday. Angrier. More focused. He says nothing. But he doesn't stop them." }
    ],
    next: "chapter_5_scene"
});
