// Chapter 14: Visibility
// Source: dialogue_storymode

var chapter14Scene = createDialogueScene({
    id: "chapter_14",
    background: "stadium",
    chapterTitle: "Chapter 14: Visibility",
    dialogue: [
        { speaker: "Narrator",      emotion: "neutral",    text: "Scene change: Match Day (vs Oakridge Away). Halcyon Coast Arena. City of cars. Attendance: 78,000. Wind off the sea. Salt in the air." },
        { speaker: "Narrator",      emotion: "neutral",    text: "YUMI'S MESSAGE: Otto's phone buzzes with an unknown number." },
        { speaker: "Unknown",       emotion: "neutral",    text: "Remember the slide where you hid your lunch money? The one with the red handle. Be there at midnight. Don't tell anyone." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Otto stares at the message. He knows instantly — it's Yumi." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Scene change: The Old Playground. Midnight. The old elementary school playground in Westward is empty and dark. Wind rustles the chains of a broken swing. Otto walks toward the back corner where a small, rusted slide sits half-hidden by overgrown bushes. He looks around. No one." },
        { speaker: "Otto",          emotion: "neutral",    text: "Yumi?" },
        { speaker: "Narrator",      emotion: "neutral",    text: "No answer. He kneels, peers into the tunnel of the slide. A shadow moves inside." },
        { speaker: "Yumi",          emotion: "neutral",    text: "Took you long enough." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Yumi crawls out, dusting off her dark clothes. Her hair is tied back, face smudged with dirt." },
        { speaker: "Yumi",          emotion: "serious",    text: "So. Have you made a decision?" },
        { speaker: "Otto",          emotion: "neutral",    text: "About what?" },
        { speaker: "Yumi",          emotion: "serious",    text: "The government's halting factory payments in Westward. They're cutting off resources to force compliance. They're going to starve people." },
        { speaker: "Otto",          emotion: "serious",    text: "What do you want?" },
        { speaker: "Narrator",      emotion: "neutral",    text: "She looks away, almost embarrassed." },
        { speaker: "Yumi",          emotion: "neutral",    text: "I actually had a crush on you at that time." },
        { speaker: "Otto",          emotion: "curious",    text: "What? How can this be true?" },
        { speaker: "Yumi",          emotion: "neutral",    text: "It's true. I never forgot." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Otto steps forward and wraps his arms around her. She tenses at first, then relaxes into the hug.",
          choices: [{ text: "Hug Yumi", next: "ch14_hug" }] },
        { speaker: "Yumi",          emotion: "neutral",    text: "That felt... natural." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Dialogue Part 2. Scene change: Holding Cell. Dim light." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Rebecca sitting alone. Bruise forming on her cheek." },
        { speaker: "Interrogator",  emotion: "serious",    text: "Tell us where they meet." },
        { speaker: "Rebecca",       emotion: "serious",    text: "I don't know." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Interrogator leans in." },
        { speaker: "Interrogator",  emotion: "serious",    text: "You think he can save you? You're his sister — you know what he's up to!" },
        { speaker: "Rebecca",       emotion: "serious",    text: "He doesn't need to." },
        { speaker: "Interrogator",  emotion: "angry",      text: "Tell me now!" },
        { speaker: "Rebecca",       emotion: "neutral",    text: "Wait, you look familiar?" },
        { speaker: "Interrogator",  emotion: "neutral",    text: "Becca? You don't remember me?" },
        { speaker: "Narrator",      emotion: "neutral",    text: "She refuses again. Door slams." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Scene change: Otto Breaks. Otto storms into underground meeting." },
        { speaker: "Rebel Leader",  emotion: "serious",    text: "They're escalating." },
        { speaker: "Otto",          emotion: "angry",      text: "They touched my family." },
        { speaker: "Leader",        emotion: "neutral",    text: "That's the price." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Otto grabs the table." },
        { speaker: "Otto",          emotion: "angry",      text: "No. That's war." },
        { speaker: "Leader",        emotion: "neutral",    text: "We will see what we can do." },
        { speaker: "Narrator",      emotion: "neutral",    text: "His anger now fuels rebellion." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Scene change: Public Event. Otto standing beside government officials at unity rally. Crowd divided. Protesters outside barricades. Chants growing louder." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Someone throws something. Police respond aggressively. Shots fired. Screams. Otto turns. Sees her fall. Time slows. He runs. Security grabs him." },
        { speaker: "Otto",          emotion: "angry",      text: "LET ME GO!" },
        { speaker: "Narrator",      emotion: "neutral",    text: "She's bleeding. Not dead. But serious. News cameras capture everything." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Scene change: Hospital. Beeping machines." },
        { speaker: "Doctor",        emotion: "neutral",    text: "She's stable... but it was close." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Otto sits alone. TV in waiting room shows government statement." },
        { speaker: "TV",            emotion: "neutral",    text: "Violence caused by extremist agitators." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Otto watches in silence. Realization setting in. Silence didn't protect her. Alignment didn't protect her." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Scene change: Presidential Response." },
        { speaker: "Vice President", emotion: "serious",   text: "The situation has escalated." },
        { speaker: "President",     emotion: "serious",    text: "Send in the secret agents." },
        { speaker: "Vice President", emotion: "serious",   text: "This could spiral." },
        { speaker: "President",     emotion: "serious",    text: "That depends on him. Let's prepare for plan Doorbell." },
        { speaker: "Narrator",      emotion: "neutral",    text: "The president looks at Otto's televised image." },
        { speaker: "President",     emotion: "serious",    text: "Let's see what he chooses now." }
    ],
    next: "chapter_22"
});
