// Chapter 2 — Selected
// Source: dialogue_storymode
// Drop additional dialogue lines into the dialogue array without breaking the engine.

var chapter2Scene = createDialogueScene({
    id: "chapter_2_scene",
    background: "apartment",
    chapterTitle: "Chapter 2: Selected",
    dialogue: [
        { speaker: "Narrator",           emotion: "neutral",    text: "Scene change: Morning — The List. Early morning light leaks through thin curtains." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Phone notification buzzes. Otto's eyes open. He doesn't move at first. He reaches for his phone. On screen: WESTWARD FC — SELECTED PLAYERS. His thumb scrolls. He stops. His name. OTTO HERRERA." },
        { speaker: "Otto",               emotion: "happy",      text: "...I made it." },
        { speaker: "Otto",               emotion: "happy",      text: "I made it. This feels... this feels so unreal." },
        { speaker: "Narrator",           emotion: "neutral",    text: "He jumps out of bed and runs into the living room." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Scene change: Living Room — Family Reaction. Rebecca is at the table, eating cereal. Josh is half-asleep on the couch." },
        { speaker: "Rebecca",            emotion: "curious",    text: "What's wrong with you?" },
        { speaker: "Narrator",           emotion: "neutral",    text: "Otto grabs the remote and turns on the TV." },
        { speaker: "News Anchor (TV)",   emotion: "neutral",    text: "Westward FC has officially announced its squad for the upcoming Western League season." },
        { speaker: "News Anchor (TV)",   emotion: "neutral",    text: "Selected players are advised to report to the training center by 10 a.m. today." },
        { speaker: "Narrator",           emotion: "neutral",    text: "The list scrolls on screen. Otto points." },
        { speaker: "Otto",               emotion: "happy",      text: "That's me, do you see my name!" },
        { speaker: "Rebecca",            emotion: "neutral",    text: "That's actually you." },
        { speaker: "Josh",               emotion: "happy",      text: "You made it?" },
        { speaker: "Amy",                emotion: "curious",    text: "You're on TV?" },
        { speaker: "Elizabeth",          emotion: "neutral",    text: "So it finally happened." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Otto nods, overwhelmed. Rebecca smirks." },
        { speaker: "Rebecca",            emotion: "happy",      text: "Good. Maybe now we can eat something other than rice and beans." },
        { speaker: "Josh",               emotion: "happy",      text: "Does this mean you're famous?" },
        { speaker: "Otto",               emotion: "serious",    text: "No. It just means I have to work even harder." },
        { speaker: "Narrator",           emotion: "neutral",    text: "He grabs his jacket." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Scene change: Outside — Reporting In. Streets packed. Soldiers everywhere. People funnel toward the training complex. Otto approaches the gate. The same soldier from tryouts steps forward." },
        { speaker: "Soldier",            emotion: "neutral",    text: "ID." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Otto hands it over. The soldier scans it, then looks up." },
        { speaker: "Soldier",            emotion: "neutral",    text: "You made it." },
        { speaker: "Narrator",           emotion: "neutral",    text: "He hands the ID back." },
        { speaker: "Soldier",            emotion: "neutral",    text: "I was reluctant about you. But congrats." },
        { speaker: "Narrator",           emotion: "neutral",    text: "He steps aside." },
        { speaker: "Soldier",            emotion: "neutral",    text: "Keep working hard. That's all I can tell you." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Otto nods and walks in." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Scene change: Team Meeting Room. Players sit in rows. Nervous energy fills the room. Coach Baker steps forward." },
        { speaker: "Coach Baker",        emotion: "serious",    text: "Congratulations. If you're sitting in this room, you made the team." },
        { speaker: "Coach Baker",        emotion: "serious",    text: "I'm not going to lie to you. This team has less depth than last year. Less talent too." },
        { speaker: "Coach Baker",        emotion: "serious",    text: "But if we're disciplined — if we work together — we can avoid last year's mistakes." },
        { speaker: "Coach Baker",        emotion: "serious",    text: "Going far in this league means money. Money means survival. For you. For your families. For Westward." },
        { speaker: "Coach Baker",        emotion: "serious",    text: "You're not just players. You're hope. That's not a small responsibility." },
        { speaker: "Coach Baker",        emotion: "serious",    text: "Report to training tomorrow morning. Be ready." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Scene change: One-on-One with Coach Baker. Otto approaches as players file out." },
        { speaker: "Otto",               emotion: "neutral",    text: "Coach... thank you. For picking me." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Coach Baker studies him for a moment." },
        { speaker: "Coach Baker",        emotion: "serious",    text: "Relax." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Otto stiffens." },
        { speaker: "Coach Baker",        emotion: "serious",    text: "You're depth. Very low on the chart." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Otto nods." },
        { speaker: "Coach Baker",        emotion: "serious",    text: "You'll need to train harder than everyone else. Maybe you get lucky and see minutes." },
        { speaker: "Coach Baker",        emotion: "serious",    text: "But don't expect much this season." },
        { speaker: "Otto",               emotion: "determined", text: "I understand. I'm going to give it my best and surprise you." },
        { speaker: "Narrator",           emotion: "neutral",    text: "He means it. And yet, he's smiling." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Scene change: Exit Gate — Brief Encounter. Otto heads out. A female security guard leans against the post." },
        { speaker: "Security Guard",     emotion: "neutral",    text: "I don't recognize you." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Otto freezes." },
        { speaker: "Otto",               emotion: "neutral",    text: "I, uh... just made the team." },
        { speaker: "Narrator",           emotion: "neutral",    text: "She smiles." },
        { speaker: "Security Guard",     emotion: "neutral",    text: "Where are you from?" },
        { speaker: "Otto",               emotion: "neutral",    text: "Outskirts of Westward." },
        { speaker: "Security Guard",     emotion: "neutral",    text: "Figures. Congrats." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Otto nods and walks off, heart pounding." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Scene change: Street Walk — The Call. Otto's phone rings. Unknown number. He answers." },
        { speaker: "Otto",               emotion: "neutral",    text: "Hello?" },
        { speaker: "Jenny (phone)",      emotion: "neutral",    text: "Hey... is this Otto Herrera?" },
        { speaker: "Narrator",           emotion: "neutral",    text: "Otto slows his steps." },
        { speaker: "Otto",               emotion: "neutral",    text: "Yeah. Who's this?" },
        { speaker: "Jenny",              emotion: "neutral",    text: "It's Jenny. Jenny Lee. Umm." },
        { speaker: "Jenny",              emotion: "neutral",    text: "We went to high school together. Same graduating class." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Otto blinks." },
        { speaker: "Otto",               emotion: "neutral",    text: "Oh — yeah. I remember." },
        { speaker: "Jenny",              emotion: "neutral",    text: "I saw your name on the list. Congratulations. No one from our high school has ever made the team." },
        { speaker: "Otto",               emotion: "neutral",    text: "Thanks." },
        { speaker: "Jenny",              emotion: "neutral",    text: "We never really talked back then... but I thought maybe we could change that." },
        { speaker: "Jenny",              emotion: "neutral",    text: "Let me take you out sometime. Coffee, lunch. My boss owns the news station and he sponsors the team. He likes to meet and get to know the players on our state team." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Otto hesitates." },
        { speaker: "Otto",               emotion: "neutral",    text: "Yeah... yeah, okay." },
        { speaker: "Jenny",              emotion: "neutral",    text: "Good. Save my number." },
        { speaker: "Narrator",           emotion: "neutral",    text: "The call ends. Otto stops walking." },
        { speaker: "Narrator",           emotion: "neutral",    text: "Scene change: Otto's Internal Voice. Otto exhales." },
        { speaker: "Otto (inner voice)", emotion: "neutral",    text: "...Jenny Lee." },
        { speaker: "Otto (inner voice)", emotion: "neutral",    text: "Oh. Jenny Lee." },
        { speaker: "Otto (inner voice)", emotion: "neutral",    text: "She was my high school crush." },
        { speaker: "Otto (inner voice)", emotion: "neutral",    text: "I thought she was the most beautiful girl in school." },
        { speaker: "Otto (inner voice)", emotion: "neutral",    text: "I was way too scared to ever talk to her." },
        { speaker: "Otto (inner voice)", emotion: "neutral",    text: "Such a dweeb." },
        { speaker: "Narrator",           emotion: "neutral",    text: "He pockets his phone and keeps walking." }
    ],
    next: "ch3_pre_game"
});
