// Prologue — Part 1: Welcome to Weston
// Source: dialogue part 1.pdf
// Drop additional dialogue lines into the dialogue array without breaking the engine.

var prologuePart1 = createDialogueScene({
    id: "prologue_01",
    background: "government_building_lobby",
    chapterTitle: "Prologue – Part 1: \"Welcome to Weston\"",
    dialogue: [
        { speaker: "Narrator",  emotion: "neutral",    text: "Black screen. Sound of ocean waves. Low mechanical hum. Fade in." },
        { speaker: "Narrator",  emotion: "neutral",    text: "A large government building sits on the edge of the ocean. A boat approaches the dock. You walk toward the building." },
        { speaker: "Girl",      emotion: "happy",      text: "Oh, hello. Welcome. I didn't hear you come in." },
        { speaker: "Girl",      emotion: "happy",      text: "My name is [INSERT NAME]. Are you just arriving from Breeder's Island?",
          choices: [{ text: "Yeah. I just came from the Breeder's Island.", next: "prologue_01_cont" }] },
        { speaker: "Girl",      emotion: "neutral",    text: "Cool. Welcome to Weston." },
        { speaker: "Girl",      emotion: "neutral",    text: "Do you have your paperwork and your ID?",
          choices: [{ text: "Yeah, I do.", next: "prologue_01_orientation" }] },
        { speaker: "Girl",      emotion: "neutral",    text: "Okay. Follow me. We have to go to the orientation building." },
        { speaker: "Girl",      emotion: "neutral",    text: "Please sit down." },
        { speaker: "Girl",      emotion: "neutral",    text: "Okay, all set. You're assigned to the city of West Ward." },
        { speaker: "Girl",      emotion: "neutral",    text: "Oh, bummer. I don't know much about West Ward." },
        { speaker: "Girl",      emotion: "neutral",    text: "But they're known for their coal mining." },
        { speaker: "Girl",      emotion: "neutral",    text: "So let me give you a tour of Weston." },
        { speaker: "Girl",      emotion: "neutral",    text: "Weston is over 1,000 years old. That's a lot of history." },
        { speaker: "Girl",      emotion: "neutral",    text: "We became one of the strongest countries in the world over 500 years ago." },
        { speaker: "Girl",      emotion: "serious",    text: "Then the Great Xiao War happened." },
        { speaker: "Girl",      emotion: "serious",    text: "It lasted over 10 years." },
        { speaker: "Girl",      emotion: "sad",        text: "It was a dark time in our history." },
        { speaker: "Girl",      emotion: "neutral",    text: "But now we made our government system for the benefit of the people." },
        { speaker: "Girl",      emotion: "happy",      text: "And people are happy." },
        { speaker: "Girl",      emotion: "neutral",    text: "Let me tell you about the basic lifeline of people who live here." },
        { speaker: "Girl",      emotion: "neutral",    text: "If you're born in West Ward, you go to the education building." },
        { speaker: "Girl",      emotion: "neutral",    text: "Every city has a common education building for elementary, middle, and high school." },
        { speaker: "Girl",      emotion: "neutral",    text: "We learn about Westward. We develop our skills. Social skills." },
        { speaker: "Girl",      emotion: "neutral",    text: "And we graduate after passing our career exam to see what kind of career we're going to take." },
        { speaker: "Girl",      emotion: "neutral",    text: "We learn the values and principles of being a Westerner." },
        { speaker: "Girl",      emotion: "neutral",    text: "We have a record of being the best students and having the best test scores in the world." },
        { speaker: "Girl",      emotion: "neutral",    text: "But for you, because you are from Breeder Island… you start off at this part of the map." },
        { speaker: "Girl",      emotion: "neutral",    text: "You go to the Selection University." },
        { speaker: "Girl",      emotion: "neutral",    text: "But I see here that you already went to university in a different country. How particular." },
        { speaker: "Girl",      emotion: "neutral",    text: "I've never seen that before." },
        { speaker: "Girl",      emotion: "neutral",    text: "But since you already have a major… and it looks like you already have a job… we can skip that." },
        { speaker: "Girl",      emotion: "neutral",    text: "But when you have kids, they will go to the Selection University for two years to master what they've been chosen to do." },
        { speaker: "Girl",      emotion: "neutral",    text: "Oh, but you start off here. In a couple of years, when you turn 25, you get to enter the Lottery Convention." },
        { speaker: "Girl",      emotion: "neutral",    text: "You will go to the Grand Lottery Convention Hall in the capital city of Draco." },
        { speaker: "Girl",      emotion: "neutral",    text: "You fill out forms. You pay your taxes." },
        { speaker: "Girl",      emotion: "neutral",    text: "Depending on your status… you can find a higher-level mate or a lower-level mate for you." },
        { speaker: "Girl",      emotion: "neutral",    text: "I wish you all the luck in that." },
        { speaker: "Girl",      emotion: "serious",    text: "But remember… mating before marriage is illegal and punishable." },
        { speaker: "Girl",      emotion: "neutral",    text: "Breeder Island-born Westerners and natural-born Westerners on the mainland are all the same." },
        { speaker: "Girl",      emotion: "serious",    text: "We have to protect each other to make sure our society survives." },
        { speaker: "Girl",      emotion: "neutral",    text: "Because without unity… there is no future.",
          choices: [{ text: "What?", next: "prologue_01_end" }] },
        { speaker: "Girl",      emotion: "neutral",    text: "Oh. Nothing." },
        { speaker: "Girl",      emotion: "neutral",    text: "Here's your ticket." },
        { speaker: "Girl",      emotion: "neutral",    text: "Here is the address of the apartment you have been given." },
        { speaker: "Girl",      emotion: "neutral",    text: "And here are 500 Westernite dollars. Use them wisely." },
        { speaker: "Girl",      emotion: "neutral",    text: "You are to report to work on Monday morning." },
        { speaker: "Girl",      emotion: "happy",      text: "Nice meeting you. Good luck." },
        { speaker: "Narrator",  emotion: "neutral",    text: "Fade to black." }
    ],
    next: "prologue_02"
});
