// Prologue — Part 1: Welcome to Weston
// Source: dialogue_storymode
// Drop additional dialogue lines into the dialogue array without breaking the engine.

var prologuePart1 = createDialogueScene({
    id: "prologue_01",
    background: "government_building_lobby",
    chapterTitle: "Prologue – Part 1: \"Welcome to Weston\"",
    dialogue: [
        { speaker: "Narrator", emotion: "neutral", text: "Black screen. Sound of ocean waves. Low mechanical hum. Fade in. Wide cinematic shot: A large, official, professional government building sits on the edge of the ocean. Clean architecture. Tall glass panels. Flags moving in the wind. A boat approaches the dock. People disembark. Camera follows the protagonist walking toward the building. Automatic doors open." },
        { speaker: "Narrator", emotion: "neutral", text: "Interior. Bright, clean, modern lobby. Reception desk at center. The cute anime girl is turned slightly away, organizing documents. She hears the door. She turns. Leans slightly toward the camera." },
        { speaker: "Girl",     emotion: "happy",   text: "Oh, hello. Welcome. I didn't hear you come in." },
        { speaker: "Girl",     emotion: "happy",   text: "My name is [INSERT NAME]. Are you just arriving from Breeder's Island?",
          choices: [{ text: "Yeah. I just came from the Breeder's Island.", next: "prologue_01_cont" }] },
        { speaker: "Girl",     emotion: "neutral", text: "Cool. Welcome to Weston." },
        { speaker: "Girl",     emotion: "neutral", text: "Do you have your paperwork and your ID?",
          choices: [{ text: "Yeah, I do.", next: "prologue_01_orientation" }] },
        { speaker: "Girl",     emotion: "neutral", text: "Okay. Follow me. We have to go to the orientation building." },
        { speaker: "Narrator", emotion: "neutral", text: "Professional presentation room overlooking the ocean. Large digital screen. She gestures to a seat." },
        { speaker: "Girl",     emotion: "neutral", text: "Please sit down." },
        { speaker: "Narrator", emotion: "neutral", text: "Presentation begins." },
        { speaker: "Girl",     emotion: "neutral", text: "Okay, all set. You're assigned to the city of West Ward." },
        { speaker: "Girl",     emotion: "neutral", text: "Oh, bummer. I don't know much about West Ward." },
        { speaker: "Girl",     emotion: "neutral", text: "But they're known for their coal mining." },
        { speaker: "Girl",     emotion: "neutral", text: "So let me give you a tour of Weston." },
        { speaker: "Girl",     emotion: "neutral", text: "Weston is over 1,000 years old. That's a lot of history." },
        { speaker: "Girl",     emotion: "neutral", text: "We became one of the strongest countries in the world over 500 years ago." },
        { speaker: "Girl",     emotion: "serious", text: "Then the Great Xiao War happened." },
        { speaker: "Girl",     emotion: "serious", text: "It lasted over 10 years." },
        { speaker: "Girl",     emotion: "sad",     text: "It was a dark time in our history." },
        { speaker: "Girl",     emotion: "neutral", text: "But now we made our government system for the benefit of the people." },
        { speaker: "Girl",     emotion: "happy",   text: "And people are happy." },
        { speaker: "Girl",     emotion: "neutral", text: "Let me tell you about the basic lifeline of people who live here." },
        { speaker: "Girl",     emotion: "neutral", text: "If you're born in West Ward, you go to the education building." },
        { speaker: "Girl",     emotion: "neutral", text: "Every city has a common education building for elementary, middle, and high school." },
        { speaker: "Girl",     emotion: "neutral", text: "We learn about Westen." },
        { speaker: "Girl",     emotion: "neutral", text: "We develop our skills." },
        { speaker: "Girl",     emotion: "neutral", text: "Social skills." },
        { speaker: "Girl",     emotion: "neutral", text: "And we graduate after passing our career exam to see what kind of career we're going to take." },
        { speaker: "Girl",     emotion: "neutral", text: "We learn the values and principles of being a Westenite." },
        { speaker: "Girl",     emotion: "neutral", text: "We have a record of being the best students and having the best test scores in the world." },
        { speaker: "Narrator", emotion: "neutral", text: "Slide changes. A highlighted map path appears." },
        { speaker: "Girl",     emotion: "neutral", text: "Then you go to the Selection University." },
        { speaker: "Girl",     emotion: "neutral", text: "But I see here that you already went to university in a different country." },
        { speaker: "Girl",     emotion: "neutral", text: "How particular." },
        { speaker: "Girl",     emotion: "neutral", text: "I've never seen that before." },
        { speaker: "Girl",     emotion: "neutral", text: "But since you already have a major..." },
        { speaker: "Girl",     emotion: "neutral", text: "And it looks like you already have a job..." },
        { speaker: "Girl",     emotion: "neutral", text: "We can skip that." },
        { speaker: "Girl",     emotion: "neutral", text: "But for you, because you are from Breeder Island..." },
        { speaker: "Girl",     emotion: "neutral", text: "When you have kids, they will go to the Selection University for two years to master what they've been chosen to do." },
        { speaker: "Girl",     emotion: "neutral", text: "Oh, but you start off here at this step — the lottery convention." },
        { speaker: "Girl",     emotion: "neutral", text: "In a couple of years, when you turn 25, you get to enter the Lottery Convention." },
        { speaker: "Girl",     emotion: "neutral", text: "You will go to the Grand Lottery Convention Hall in the capital city of Draco." },
        { speaker: "Girl",     emotion: "neutral", text: "You fill out forms." },
        { speaker: "Girl",     emotion: "neutral", text: "You pay your taxes." },
        { speaker: "Girl",     emotion: "neutral", text: "Depending on your status..." },
        { speaker: "Girl",     emotion: "neutral", text: "You can find a higher-level mate or a lower-level mate for you." },
        { speaker: "Girl",     emotion: "neutral", text: "I wish you all the luck in that." },
        { speaker: "Girl",     emotion: "neutral", text: "But remember..." },
        { speaker: "Girl",     emotion: "serious", text: "Mating before marriage is illegal and punishable." },
        { speaker: "Girl",     emotion: "neutral", text: "Breeder Island-born Westenites and natural-born Westenites on the mainland are all the same." },
        { speaker: "Girl",     emotion: "serious", text: "We have to protect each other to make sure our society survives." },
        { speaker: "Girl",     emotion: "neutral", text: "Because without unity there is no future.",
          choices: [{ text: "What?", next: "prologue_01_end" }] },
        { speaker: "Girl",     emotion: "neutral", text: "Oh. Nothing." },
        { speaker: "Girl",     emotion: "neutral", text: "Here's your ticket." },
        { speaker: "Girl",     emotion: "neutral", text: "Here is the address of the apartment you have been given." },
        { speaker: "Girl",     emotion: "neutral", text: "And here are 500 Westernite dollars." },
        { speaker: "Girl",     emotion: "neutral", text: "Use them wisely." },
        { speaker: "Girl",     emotion: "neutral", text: "You are to report to work on Monday morning." },
        { speaker: "Girl",     emotion: "happy",   text: "Nice meeting you." },
        { speaker: "Girl",     emotion: "happy",   text: "Good luck." },
        { speaker: "Narrator", emotion: "neutral", text: "Fade to black. End Prologue Part 1." }
    ],
    next: "prologue_02"
});
