// Chapter 5 — "Pressure Makes Shapes"
// Source: dialogue_storymode

var chapter5Scene = createDialogueScene({
    id: "chapter_5_scene",
    background: "training_ground",
    chapterTitle: "Chapter 5: Pressure Makes Shapes",
    dialogue: [
        { speaker: "Narrator",      emotion: "neutral",    text: "Pre-Match Interview. Away vs Ashbourne." },
        { speaker: "Interviewer",   emotion: "neutral",    text: "Westward travels to the third-largest city in the nation tonight. Financial capital. Loud crowd. Thoughts, Coach?" },
        { speaker: "Coach Baker",   emotion: "serious",    text: "They've got money. We've got legs." },
        { speaker: "Interviewer",   emotion: "neutral",    text: "And Otto Herrera after last match?" },
        { speaker: "Narrator",      emotion: "neutral",    text: "Baker pauses just long enough." },
        { speaker: "Coach Baker",   emotion: "neutral",    text: "He earned more minutes." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Scene change: Training Escalation. Morning. Training ground. Urban skyline looming beyond the fences." },
        { speaker: "Coach Baker",   emotion: "serious",    text: "Yesterday's heroics don't carry over." },
        { speaker: "Narrator",      emotion: "neutral",    text: "He blows the whistle." },
        { speaker: "Coach Baker",   emotion: "serious",    text: "Double sessions. Faster transitions. Herrera — up top." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Otto nods. His body feels heavier than yesterday. Otto finishes a sprint late. Hands on knees. He hides it." },
        { speaker: "Teammate",      emotion: "curious",    text: "You good?" },
        { speaker: "Otto",          emotion: "neutral",    text: "Yeah. Just… morning legs." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Whistle blows." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Scene change: Health Management. Locker room. Otto sits alone, injecting insulin discreetly. His hands shake — not fear. Exhaustion. The door opens. Coach Baker stands there, having walked in on him. Otto freezes, syringe in hand. A beat of tense silence." },
        { speaker: "Coach Baker",   emotion: "serious",    text: "Training room. After practice. Every day." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Otto nods, unable to speak. Coach turns and leaves without another word." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Scene change: Match Day. Night. Massive stadium. LED billboards." },
        { speaker: "Announcer",     emotion: "neutral",    text: "Welcome to the financial heart of Weston!" },
        { speaker: "Narrator",      emotion: "neutral",    text: "Otto steps onto the pitch as a starter. The match is fast. Technical. Ruthless. Otto presses. Wins a ball. One-touch pass. Assist. Later — late run into the box. Goal. Final Score: Westward wins." },
        { speaker: "Interviewer",   emotion: "neutral",    text: "Another strong performance. People are starting to say your name. How do you handle that?" },
        { speaker: "Otto",          emotion: "neutral",    text: "I don't think about names. I think about tomorrow." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Crowd murmurs approvingly." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Scene change: City Night — Aftermath. Neon lights. Glass towers. A city that feels unreal." },
        { speaker: "Teammate 1",    emotion: "neutral",    text: "This place doesn't sleep." },
        { speaker: "Teammate 2",    emotion: "neutral",    text: "This place doesn't forgive either." },
        { speaker: "Narrator",      emotion: "neutral",    text: "They laugh, nervous." },
        { speaker: "Teammate 1",    emotion: "neutral",    text: "One drink." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Otto hesitates." },
        { speaker: "Otto",          emotion: "neutral",    text: "One." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Scene change: The Club. Small club. Music low enough to talk. Otto bumps into someone." },
        { speaker: "Olivia",        emotion: "neutral",    text: "Oh — sorry." },
        { speaker: "Narrator",      emotion: "neutral",    text: "She looks up. Recognizes him. She laughs." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Location: Outside a stylish club in Westward — late evening. Otto steps outside to escape the loud music, pulling out his phone." },
        { speaker: "Otto (inner voice)", emotion: "curious", text: "Was she looking at me or just… looking around?" },
        { speaker: "Narrator",      emotion: "neutral",    text: "He scrolls through his phone, then leans against the wall, exhaling slowly." },
        { speaker: "Olivia",        emotion: "neutral",    text: "You look tired." },
        { speaker: "Otto",          emotion: "neutral",    text: "Oh — hey. Yeah, these games… they're more than just skill." },
        { speaker: "Olivia",        emotion: "happy",      text: "You're a really good player. Your team's doing well — first time in 50 years, I heard." },
        { speaker: "Otto",          emotion: "curious",    text: "You watch my games? You know who I am?" },
        { speaker: "Olivia",        emotion: "neutral",    text: "Yeah, you're Otto. It's like you're catching on really quick around Weston." },
        { speaker: "Otto",          emotion: "neutral",    text: "Wait, you know me? I didn't even know people outside Westward watched us." },
        { speaker: "Narrator",      emotion: "neutral",    text: "He looks away, slightly flustered." },
        { speaker: "Olivia",        emotion: "neutral",    text: "Are you a little shy? I've seen you around. You're… getting famous. Like an underdog story famous. Maybe more than the rich or the models in Weston." },
        { speaker: "Otto",          emotion: "happy",      text: "No, no. You're the model. You're very beautiful." },
        { speaker: "Olivia",        emotion: "happy",      text: "Let me help you — don't be shy. Just be yourself." },
        { speaker: "Narrator",      emotion: "neutral",    text: "She gestures toward a quieter spot down the street." },
        { speaker: "Olivia",        emotion: "neutral",    text: "Walk with me? I need to get some of these tacos from that food stand for my friend." },
        { speaker: "Otto",          emotion: "happy",      text: "Ok. Tacos sound good actually." },
        { speaker: "Narrator",      emotion: "neutral",    text: "At the food stand. Olivia turns to face him." },
        { speaker: "Olivia",        emotion: "serious",    text: "You know, in the capital, they instill it in us from childhood about how to think in life. They make us watch soccer matches in school, and then they impart a lesson far beyond the sport." },
        { speaker: "Otto",          emotion: "curious",    text: "What lesson?" },
        { speaker: "Olivia",        emotion: "serious",    text: "That the game is never confined to the field." },
        { speaker: "Olivia",        emotion: "serious",    text: "Often, the most decisive moves are the invisible ones. The ones executed in silence, when you believe no one is watching." },
        { speaker: "Olivia",        emotion: "serious",    text: "Be mindful of the squares upon which you choose to land." },
        { speaker: "Otto",          emotion: "curious",    text: "What are you implying?" },
        { speaker: "Olivia",        emotion: "neutral",    text: "Steer clear of the observers. Remain alert for openings." },
        { speaker: "Olivia",        emotion: "neutral",    text: "You strike me as someone who understands the value of moving without sound." },
        { speaker: "Otto",          emotion: "sad",        text: "I'm not particularly good at anything, it seems." },
        { speaker: "Olivia",        emotion: "neutral",    text: "You'll comprehend it in time… provided your intentions remain true." },
        { speaker: "Otto",          emotion: "neutral",    text: "What are you suggesting? I don't consider myself a bad person." },
        { speaker: "Olivia",        emotion: "neutral",    text: "I never said you were." },
        { speaker: "Otto",          emotion: "curious",    text: "Then why share all of this with me?" },
        { speaker: "Olivia",        emotion: "neutral",    text: "I appreciate football for reasons that transcend the spectacle. And you… you appear to be playing for something greater than yourself." },
        { speaker: "Otto",          emotion: "neutral",    text: "Truthfully, I'm playing for myself. To provide for my sisters. I'm uncertain whether I should concern myself with others… I was left to care for my siblings. Forming connections has never been a strength. I don't believe I should worry about other people when I've always been alone. Always lagging behind… in perception, in understanding." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Olivia observes him, her expression softening." },
        { speaker: "Olivia",        emotion: "neutral",    text: "Otto… that quiet voice within you can be deceptive. You must learn to trust in yourself. I perceive something different in you." },
        { speaker: "Otto",          emotion: "curious",    text: "What do you see?" },
        { speaker: "Olivia",        emotion: "neutral",    text: "I've watched football since I was a child. I've never seen a team play quite like yours. There's a certain… conviction in your team's style. You guys play free and it describes the way Westward people live and their dreams they see in y'all." },
        { speaker: "Otto",          emotion: "neutral",    text: "I am just beginning to know my teammates. They seem like nice people. I'm unsure if true bonds form quickly… but I will endeavor to contribute to the team. As I said… trust does not come easily to me." },
        { speaker: "Olivia",        emotion: "neutral",    text: "I understand. Simply remember… not every observer is an adversary. Some of us are merely waiting to witness what you become." },
        { speaker: "Olivia",        emotion: "curious",    text: "Why do you harbor such doubt in yourself?" },
        { speaker: "Otto",          emotion: "sad",        text: "What if I falter? What if I am merely… what they always said I was? That I would amount to nothing. That my surname is different. That I am weird. That I am simply… inadequate." },
        { speaker: "Olivia",        emotion: "serious",    text: "Listen to me. So long as you devote yourself entirely — authentically and completely — and leverage every resource your club now affords you… the nourishment, the training, the visibility… and you depart with no remorse when all is concluded… that is what signifies. That you offered everything." },
        { speaker: "Olivia",        emotion: "serious",    text: "That endeavor will not haunt you in later years. When you are elsewhere — with grandchildren, a spouse, in retirement reflecting upon your life — you will be able to affirm that you withheld nothing from the pitch. Not your talent, not your passion, not your opportunity. And that… that constitutes a life lived without regret." },
        { speaker: "Otto",          emotion: "neutral",    text: "Why don't they teach us that in the schools in Westward?" },
        { speaker: "Olivia",        emotion: "neutral",    text: "That, right there, is precisely why you must continue to play." },
        { speaker: "Narrator",      emotion: "neutral",    text: "She turns to leave, then glances back a final time." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Scene change: The Club. They sit." },
        { speaker: "Olivia",        emotion: "neutral",    text: "So. Soccer boy in the city." },
        { speaker: "Otto",          emotion: "neutral",    text: "I don't live anywhere like this." },
        { speaker: "Olivia",        emotion: "neutral",    text: "I do. Trust me — it gets boring." },
        { speaker: "Otto",          emotion: "neutral",    text: "You don't sound bored." },
        { speaker: "Olivia",        emotion: "neutral",    text: "That's because I pretend." },
        { speaker: "Narrator",      emotion: "neutral",    text: "She studies him." },
        { speaker: "Olivia",        emotion: "neutral",    text: "You don't pretend well." },
        { speaker: "Otto",          emotion: "neutral",    text: "I don't know how." },
        { speaker: "Narrator",      emotion: "neutral",    text: "She nods. Respect." },
        { speaker: "Olivia",        emotion: "serious",    text: "People see athletes like trophies but they're just false idols… but they give people confidence to look for a better life, while the rich keep the cripples and sheep down." },
        { speaker: "Otto",          emotion: "neutral",    text: "I just want to keep winning. I just want…" },
        { speaker: "Olivia",        emotion: "curious",    text: "A visa?" },
        { speaker: "Otto",          emotion: "neutral",    text: "Happiness, but I need money and a visa wouldn't hurt right now. Who am I to give people hope? I'm lost." },
        { speaker: "Olivia",        emotion: "happy",      text: "You should pray, and keep your heart pure. Haha." },
        { speaker: "Olivia",        emotion: "neutral",    text: "Enjoy the city while it's kind to you. Things will change quickly… everything does. Well, I need to get back to my friends. Thanks for the company. I must go back inside the club." },
        { speaker: "Olivia",        emotion: "neutral",    text: "Goodnight, Otto. Take care of yourself… and your sisters." },
        { speaker: "Narrator",      emotion: "neutral",    text: "Scene change: Back at the Hotel. Otto collapses on the bed. Phone buzzes. Messages from fans. Clips. Unknown follows. He turns the phone face-down." }
    ],
    next: "chapter_6_scene"
});
