// Chapter 1 — The Westen-Xiao League
// Source: dialogue_storymode
// Drop additional dialogue lines into the dialogue array without breaking the engine.

var chapter1Scene = createDialogueScene({
    id: "chapter_1_scene",
    background: "apartment",
    chapterTitle: "Chapter 1: The Westen-Xiao League",
    dialogue: [
        { speaker: "Narrator",     emotion: "neutral",    text: "Scene change: The Apartment. Evening. Small, cramped apartment. Otto enters, exhausted from work." },
        { speaker: "Rebecca",      emotion: "neutral",    text: "You're late again." },
        { speaker: "Otto",         emotion: "neutral",    text: "I had to stay." },
        { speaker: "Rebecca",      emotion: "neutral",    text: "You look dead." },
        { speaker: "Rebecca",      emotion: "curious",    text: "Hey — today at school everyone was talking about the tryouts and the new season that's coming. You're gonna go try out in a couple of days, right?" },
        { speaker: "Narrator",     emotion: "neutral",    text: "Otto doesn't answer right away." },
        { speaker: "Elizabeth",    emotion: "serious",    text: "You can't give up." },
        { speaker: "Elizabeth",    emotion: "serious",    text: "I've seen you play. You're so good." },
        { speaker: "Otto",         emotion: "neutral",    text: "I don't know yet." },
        { speaker: "Otto",         emotion: "neutral",    text: "But I probably will." },
        { speaker: "Rebecca",      emotion: "neutral",    text: "You better." },
        { speaker: "Rebecca",      emotion: "neutral",    text: "I'm tired of eating rice and beans almost every day." },
        { speaker: "Elizabeth",    emotion: "neutral",    text: "Yeah. You say this every year." },
        { speaker: "Elizabeth",    emotion: "neutral",    text: "And every year, you still go." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Otto exhales." },
        { speaker: "Otto",         emotion: "neutral",    text: "Yeah, you're right." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Scene change: The Breakup. Morgan enters the room." },
        { speaker: "Morgan",       emotion: "serious",    text: "Otto... can I talk to you?" },
        { speaker: "Narrator",     emotion: "neutral",    text: "Scene change: Outside. Night. They stand under a flickering light." },
        { speaker: "Morgan",       emotion: "serious",    text: "I'm leaving." },
        { speaker: "Morgan",       emotion: "serious",    text: "I got selected." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Otto stiffens." },
        { speaker: "Otto",         emotion: "sad",        text: "Baby, what are you saying?" },
        { speaker: "Morgan",       emotion: "neutral",    text: "The government selected me to be a model." },
        { speaker: "Morgan",       emotion: "neutral",    text: "I'm going to the capital." },
        { speaker: "Morgan",       emotion: "serious",    text: "Otto, I deserve more." },
        { speaker: "Morgan",       emotion: "serious",    text: "I can't wait forever." },
        { speaker: "Morgan",       emotion: "serious",    text: "You've been trying for years." },
        { speaker: "Morgan",       emotion: "serious",    text: "And you're still here." },
        { speaker: "Morgan",       emotion: "serious",    text: "You're messy." },
        { speaker: "Morgan",       emotion: "serious",    text: "You need to fix yourself." },
        { speaker: "Morgan",       emotion: "serious",    text: "I can do better." },
        { speaker: "Morgan",       emotion: "serious",    text: "You're a loser. And it took me a while but you're lame." },
        { speaker: "Narrator",     emotion: "neutral",    text: "She leaves. Otto stays standing." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Scene change: Back Inside. Otto sits alone. He injects insulin. Stares at the floor." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Scene change: Tryout Morning. Early morning. Otto wakes up. Eats hard-boiled eggs. Chugs a bottle of electrolytes." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Scene change: The Streets. The town is packed. Roads closed. People flooding toward the stadium. Otto walks." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Scene change: Training Facility Gate. Soldiers guard the entrance. One steps forward." },
        { speaker: "Soldier",      emotion: "serious",    text: "You trying out?" },
        { speaker: "Narrator",     emotion: "neutral",    text: "Otto hands it over. The soldier scans it. Looks Otto up and down." },
        { speaker: "Soldier",      emotion: "serious",    text: "You look weak." },
        { speaker: "Soldier",      emotion: "neutral",    text: "But you're on the list." },
        { speaker: "Soldier",      emotion: "neutral",    text: "Here's your ID back." },
        { speaker: "Soldier",      emotion: "neutral",    text: "Go on." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Scene change: The Field. Players warming up. Tense. Silent. Coach steps forward." },
        { speaker: "Coach Baker",  emotion: "serious",    text: "Listen up." },
        { speaker: "Coach Baker",  emotion: "serious",    text: "If you're here to dream — leave now." },
        { speaker: "Narrator",     emotion: "neutral",    text: "No one moves." },
        { speaker: "Coach Baker",  emotion: "serious",    text: "And if you made the team last year... that means nothing." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Whistle blows. Fade out." }
    ],
    next: "chapter_2_scene"
});
