// Chapter 3 — "First Test"
// Source: dialogue_storymode

var chapter3StoryScene = createDialogueScene({
    id: "chapter_3_scene",
    background: "training_ground",
    chapterTitle: "Chapter 3: First Test",
    dialogue: [
        { speaker: "Narrator",     emotion: "neutral",    text: "Pre-Match Interview. TV / Radio Feed." },
        { speaker: "Interviewer",  emotion: "neutral",    text: "Coach Baker, opening match of the Western League. Away game. What are your expectations?" },
        { speaker: "Coach Baker",  emotion: "serious",    text: "Expectations? Survival. We're young. We're thin. But we're disciplined. If we stay organized and don't panic, we give ourselves a chance." },
        { speaker: "Interviewer",  emotion: "neutral",    text: "Any surprises in the lineup?" },
        { speaker: "Coach Baker",  emotion: "serious",    text: "No surprises. Rookies learn first. Minutes come later." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Camera cuts. Static." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Scene change: Training. Morning. Training ground. The sound of cleats hitting dirt. Whistles. Shouting." },
        { speaker: "Coach Baker",  emotion: "serious",    text: "Line up! Shoulder to shoulder!" },
        { speaker: "Narrator",     emotion: "neutral",    text: "Players rush. Otto jogs into line, slightly out of breath." },
        { speaker: "Coach Baker",  emotion: "serious",    text: "This week isn't about talent. It's about nerves. Tomorrow you walk into a stadium that eats players alive." },
        { speaker: "Narrator",     emotion: "neutral",    text: "He paces." },
        { speaker: "Coach Baker",  emotion: "serious",    text: "Sixty thousand people. Noise. Pressure. Cameras. You forget fundamentals, you disappear." },
        { speaker: "Narrator",     emotion: "neutral",    text: "He stops in front of the rookies." },
        { speaker: "Coach Baker",  emotion: "serious",    text: "For you new guys — this is an away match. One of the finalists from last year. They smell weakness." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Coach locks eyes briefly with Otto, then moves on." },
        { speaker: "Coach Baker",  emotion: "serious",    text: "Bench players — pay attention. You don't get minutes by wanting them. You get minutes by being ready." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Training begins. Sprints. Passing drills. Pressing. Otto finishes a sprint late. Hands on knees. He hides it." },
        { speaker: "Teammate",     emotion: "curious",    text: "You good?" },
        { speaker: "Otto",         emotion: "neutral",    text: "Yeah. Just… morning legs." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Whistle blows." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Scene change: Lineup Announcement. Locker room. The mood is tense." },
        { speaker: "Coach Baker",  emotion: "serious",    text: "Tomorrow's squad." },
        { speaker: "Narrator",     emotion: "neutral",    text: "He reads names. Starters first. Then subs." },
        { speaker: "Coach Baker",  emotion: "serious",    text: "...Herrera. Bench." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Otto nods. Expected. Still stings." },
        { speaker: "Coach Baker",  emotion: "serious",    text: "Be early. Be quiet. Watch everything." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Meeting breaks." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Scene change: Night. Otto sits on his bed. Phone buzzes." },
        { speaker: "Jenny (text)", emotion: "neutral",    text: "So… first league match tomorrow?" },
        { speaker: "Otto (text)",  emotion: "neutral",    text: "Yeah. Away. Big stadium." },
        { speaker: "Jenny (text)", emotion: "curious",    text: "Nervous?" },
        { speaker: "Otto (text)",  emotion: "neutral",    text: "Terrified." },
        { speaker: "Jenny (text)", emotion: "neutral",    text: "Good. Means you care." },
        { speaker: "Jenny (text)", emotion: "neutral",    text: "Dinner tonight? Strictly 'business.'" },
        { speaker: "Otto (text)",  emotion: "curious",    text: "Business?" },
        { speaker: "Jenny (text)", emotion: "neutral",    text: "Catching up. No pressure." },
        { speaker: "Otto (inner voice)", emotion: "neutral", text: "Business dinner with my high school crush. Sure. Totally normal." },
        { speaker: "Otto (text)",  emotion: "neutral",    text: "Okay." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Scene change: Dinner with Jenny. Small café. Dim lighting. Quiet." },
        { speaker: "Jenny",        emotion: "curious",    text: "You look… different." },
        { speaker: "Otto",         emotion: "curious",    text: "Worse or better?" },
        { speaker: "Jenny",        emotion: "neutral",    text: "Realer." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Otto laughs, surprised." },
        { speaker: "Otto",         emotion: "neutral",    text: "You were impossible to talk to in high school." },
        { speaker: "Jenny",        emotion: "curious",    text: "Because I was popular?" },
        { speaker: "Otto",         emotion: "neutral",    text: "No. Because I was scared." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Jenny softens." },
        { speaker: "Jenny",        emotion: "sad",        text: "I wasn't as happy as I looked." },
        { speaker: "Otto",         emotion: "neutral",    text: "I thought you had everything." },
        { speaker: "Jenny",        emotion: "neutral",    text: "And I thought you were brave. Always running. Always trying." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Silence. Comfortable." },
        { speaker: "Jenny",        emotion: "curious",    text: "So… soccer saved you?" },
        { speaker: "Otto",         emotion: "neutral",    text: "It's the only place I forget everything else." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Jenny nods, remembering that." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Scene change: Match Day. The Stadium. Exterior. Massive stadium. Crowds roar. Otto steps off the bus. He freezes." },
        { speaker: "Otto (inner voice)", emotion: "serious", text: "So many people…" },
        { speaker: "Narrator",     emotion: "neutral",    text: "Locker room." },
        { speaker: "Coach Baker",  emotion: "serious",    text: "Listen. You hear that noise? That's fear. Use it or let it crush you." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Otto sits. Bench. Watching." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Scene change: The Match. Kickoff. The opposing team dominates early. Westward struggles." },
        { speaker: "Announcer",    emotion: "neutral",    text: "Westward looking overwhelmed in the opening minutes—" },
        { speaker: "Narrator",     emotion: "neutral",    text: "Otto watches every movement. Every mistake. Final whistle. Result determined by simulation — loss, draw, or narrow win." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Post-match interview." },
        { speaker: "Interviewer",  emotion: "neutral",    text: "Tough environment. Thoughts?" },
        { speaker: "Coach Baker",  emotion: "serious",    text: "We survived. That's step one." },
        { speaker: "Narrator",     emotion: "neutral",    text: "Scene change: Bus ride home. Night. Otto checks his phone." },
        { speaker: "Jenny (text)", emotion: "neutral",    text: "You didn't play." },
        { speaker: "Otto (text)",  emotion: "neutral",    text: "No." },
        { speaker: "Jenny (text)", emotion: "neutral",    text: "But you belonged there." },
        { speaker: "Otto (inner voice)", emotion: "curious", text: "Did I?" }
    ],
    next: "chapter_golden_return"
});
