// Chapter: They Say It Out Loud
// Source: dialogue_storymode

var chapterTheySayItOutLoudScene = createDialogueScene({
    id: "chapter_they_say_it_out_loud",
    background: "westward_locker_room",
    chapterTitle: "They Say It Out Loud",
    dialogue: [
        { speaker: "Narrator",       emotion: "neutral",    text: "Scene change: Westward Locker Room. Night. The team crowds around the TV again. Same station. Different segment. A rival player from another club sits comfortably in a studio chair, arms crossed." },
        { speaker: "Anchor",         emotion: "neutral",    text: "You're facing Westward next." },
        { speaker: "Rival Player",   emotion: "neutral",    text: "Yeah. We saw the schedule." },
        { speaker: "Anchor",         emotion: "neutral",    text: "Any concerns?" },
        { speaker: "Rival Player",   emotion: "serious",    text: "Look, let's stop pretending." },
        { speaker: "Rival Player",   emotion: "serious",    text: "Westward doesn't have discipline. They don't have structure. Their people..." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Scene change: City Night — Aftermath. Neon lights. Glass towers. A city that feels unreal." },
        { speaker: "Teammate 1",     emotion: "neutral",    text: "This place doesn't sleep." },
        { speaker: "Teammate 2",     emotion: "neutral",    text: "This place doesn't forgive either." },
        { speaker: "Narrator",       emotion: "neutral",    text: "They laugh, nervous." },
        { speaker: "Teammate 1",     emotion: "neutral",    text: "One drink." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Otto hesitates." },
        { speaker: "Otto",           emotion: "neutral",    text: "One." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Scene change: The Club. Small club. Music low enough to talk. Otto bumps into someone." },
        { speaker: "Olivia",         emotion: "neutral",    text: "Oh..." },
        { speaker: "Narrator",       emotion: "neutral",    text: "82nd minute. One broken press. One mistake. Otto cuts inside. No hesitation. He shoots. Silence — then eruption. Westward scores. They hold on. Final Score: Westward wins. Northfield loses." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Scene change: MVP Ceremony. Fireworks crackle overhead. Otto stands awkwardly on a small stage. A woman approaches holding the Match MVP plaque. Poised. Sharp. Confident. Ashley. Her boss leans in behind her." },
        { speaker: "Ashley's Boss",  emotion: "neutral",    text: "You present it." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Ashley nods. She hands Otto the award. Their fingers brush." },
        { speaker: "Ashley",         emotion: "neutral",    text: "Otto Herrera. Match MVP." },
        { speaker: "Otto",           emotion: "neutral",    text: "...Thank you." },
        { speaker: "Narrator",       emotion: "neutral",    text: "She smiles — just a little." },
        { speaker: "Ashley",         emotion: "neutral",    text: "Not bad for a depth player." },
        { speaker: "Otto",           emotion: "curious",    text: "You watched?" },
        { speaker: "Ashley",         emotion: "neutral",    text: "I was forced to. It's my job." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Their eyes linger a second too long." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Scene change: Formal Introduction. The next day. Government complex. Neutral halls. Ashley meets Otto properly this time." },
        { speaker: "Ashley",         emotion: "neutral",    text: "Otto Herrera." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Otto opens the folder. Inside are not just league profiles, but surveillance notes, financial records of team sponsors, and a highlighted section about 'narrative influence.' At the bottom of the last page, a handwritten note: 'Your insulin shipments have been flagged for review. — A'" },
        { speaker: "Rebecca (text)", emotion: "neutral",    text: "Someone from the school board came by today. Asked about you. They were... polite. But it felt wrong." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Otto stares at the note, then at the door Ashley left through." },
        { speaker: "Otto",           emotion: "serious",    text: "Was this a threat or a warning?",
          choices: [{ text: "Confront Ashley directly", next: null }] },
        { speaker: "Ashley",         emotion: "neutral",    text: "It's data. What you do with it determines the category." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Otto texts Olivia." },
        { speaker: "Olivia",         emotion: "neutral",    text: "So. What did you want to talk about?" },
        { speaker: "Otto",           emotion: "neutral",    text: "I just wanted to get to know you more. You left me thinking about you the other day. Things you said — you seem like an interesting person. Can you tell me more about what's going on in the government? You said you want to make changes." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Olivia's smile fades slightly. She takes a slow sip from her fresh pint." },
        { speaker: "Olivia",         emotion: "serious",    text: "Only a certain amount of people really have the power in Weston. And they're lying. But... they give us a good life. Me and my family. A good life." },
        { speaker: "Narrator",       emotion: "neutral",    text: "She looks down into her glass." },
        { speaker: "Olivia",         emotion: "sad",        text: "My dad... he's getting sad. Regretting his decisions in life. My mom's happy to be rich, but my dad... it's hitting him hard. He's in his office a lot of the times at home. He drinks a lot. And he teaches me things... some things I can't really tell you. Unless I really trust you." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Scene change: After the Incident. The bus reroutes, arrives back at the stadium. Players are shaken. Otto gets a call." },
        { speaker: "Jenny",          emotion: "serious",    text: "Are you okay? I saw the footage." },
        { speaker: "Otto",           emotion: "neutral",    text: "Yeah. We're safe. We're locked in the stadium now." },
        { speaker: "Jenny",          emotion: "neutral",    text: "Do you know when you'll be out?" },
        { speaker: "Otto",           emotion: "neutral",    text: "Honestly? No." },
        { speaker: "Jenny",          emotion: "neutral",    text: "I happen to be in town. In Westward. I wanted to see you." },
        { speaker: "Jenny",          emotion: "neutral",    text: "But you're different." },
        { speaker: "Otto",           emotion: "curious",    text: "Is that good?" },
        { speaker: "Jenny",          emotion: "neutral",    text: "Maybe. You're just lucky that you're kind of cute. In an ugly way." },
        { speaker: "Otto",           emotion: "neutral",    text: "I don't know how to take that, but I'll take my chances." },
        { speaker: "Jenny",          emotion: "neutral",    text: "Yeah. Next home game, my boss will be at the stadium. I'll introduce you to him." },
        { speaker: "Otto",           emotion: "neutral",    text: "I guess." },
        { speaker: "Jenny",          emotion: "neutral",    text: "You might want to have him as a friend. He's helped me a lot through some tough times." },
        { speaker: "Otto",           emotion: "neutral",    text: "Can I take your word for it?" },
        { speaker: "Jenny",          emotion: "neutral",    text: "We went to the same high school. I know where you live. If I wanted to do something, I would've done it by now." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Ashley pauses, doesn't turn." },
        { speaker: "Ashley",         emotion: "neutral",    text: "Don't thank me yet." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Then she's gone." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Scene change: Jenny's Call. Otto's phone rings ten minutes after Ashley leaves. It's Jenny. Her voice is a hushed, tense whisper." },
        { speaker: "Jenny",          emotion: "serious",    text: "Otto, it's getting worse. My boss — he's always fought for the truth. But now he's screaming at everyone to pull stories, kill segments. He's scared. I've never seen him scared." },
        { speaker: "Otto",           emotion: "serious",    text: "What aren't they telling us?" },
        { speaker: "Jenny",          emotion: "serious",    text: "I don't know. But it's not just Westward. It's everywhere. They're scrubbing feeds, deleting archives. This is bigger than football. This is about who gets to tell the story." },
        { speaker: "Narrator",       emotion: "neutral",    text: "A beat. Otto can hear her breathing — shallow, nervous." },
        { speaker: "Otto",           emotion: "neutral",    text: "Wait. I need to ask you something before I let you go." },
        { speaker: "Jenny",          emotion: "neutral",    text: "Okay. What is it?" },
        { speaker: "Narrator",       emotion: "neutral",    text: "Scene change: Match Day — Rowdy Atmosphere. Despite the tension, the stadium is packed. Fans are sitting on laps, standing in aisles, pressed against fences. It's a home game, and Westward has never needed a win more." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Otto scores early. The roar is deafening. But by the second half, protests erupt outside the gates. The sound of sirens blends with cheers. Final whistle: Westward wins 2-1. But as the players head to the tunnel, fans storm the field — not in celebration, but in protest. Security swarms. Otto is shoved toward the locker room." },
        { speaker: "Coach Baker",    emotion: "serious",    text: "Don't stop! Don't look back! Go!" },
        { speaker: "Narrator",       emotion: "neutral",    text: "In the locker room, they can still hear the chants: NO JUSTICE, NO PEACE." },
        { speaker: "Olivia",         emotion: "serious",    text: "I'm not lying to you, Otto." },
        { speaker: "Narrator",       emotion: "neutral",    text: "Scene change: The Evening News. Back in the dormitory, the team watches Jenny on screen. She looks pale under the studio lights." },
        { speaker: "Jenny (on screen)", emotion: "neutral", text: "Several Westward residents were arrested today in connection with underground news distribution." },
        { speaker: "Jenny (on screen)", emotion: "neutral", text: "Authorities warn that anyone caught consuming or sharing illegal broadcasts will be detained." },
        { speaker: "Narrator",       emotion: "neutral",    text: "She lists names. Otto recognizes two — a guy he played street ball with, a woman who worked at the grocery store." },
        { speaker: "Jenny (on screen)", emotion: "neutral", text: "The state reminds citizens that unity is our strength." },
        { speaker: "Jenny (on screen)", emotion: "neutral", text: "Division will not be tolerated." },
        { speaker: "Narrator",       emotion: "neutral",    text: "The broadcast cuts to a commercial. The room is silent." },
        { speaker: "Teammate",       emotion: "serious",    text: "They're making examples." },
        { speaker: "Otto",           emotion: "serious",    text: "Whatever's coming... it's bigger than football. Things just changed." },
        { speaker: "Narrator",       emotion: "neutral",    text: "He looks at his phone. No new messages. Just the quiet before the storm." }
    ],
    next: "chapter_12"
});
