// Unnumbered Chapter — Dinner
// Source: dialogue_storymode

var chapterDinnerScene = createDialogueScene({
    id: "chapter_dinner",
    background: "family_apartment",
    chapterTitle: "Dinner",
    dialogue: [
        { speaker: "Narrator",   emotion: "neutral",    text: "Interior. Mei Ling's family apartment. Night. A small kitchen. Clean, but tired. Mei Ling sits at the table with her mother. Dinner is getting cold. The door opens." },
        { speaker: "Narrator",   emotion: "neutral",    text: "Her father steps in — shoulders heavy, face lined with exhaustion." },
        { speaker: "Mei Ling",   emotion: "curious",    text: "Dad?" },
        { speaker: "Narrator",   emotion: "neutral",    text: "He forces a smile." },
        { speaker: "Father",     emotion: "neutral",    text: "Sorry I'm late." },
        { speaker: "Mother",     emotion: "neutral",    text: "You're always late now." },
        { speaker: "Narrator",   emotion: "neutral",    text: "He sets his bag down carefully." },
        { speaker: "Father",     emotion: "neutral",    text: "There was... an issue." },
        { speaker: "Narrator",   emotion: "neutral",    text: "They sit." },
        { speaker: "Mei Ling",   emotion: "curious",    text: "What kind of issue?" },
        { speaker: "Narrator",   emotion: "neutral",    text: "He hesitates." },
        { speaker: "Father",     emotion: "neutral",    text: "I spoke up." },
        { speaker: "Narrator",   emotion: "neutral",    text: "Mother's eyes narrow." },
        { speaker: "Mother",     emotion: "serious",    text: "You did what?" },
        { speaker: "Father",     emotion: "neutral",    text: "They were blaming a worker for something he didn't do." },
        { speaker: "Mei Ling",   emotion: "neutral",    text: "And?" },
        { speaker: "Father",     emotion: "neutral",    text: "And now I've been reassigned." },
        { speaker: "Narrator",   emotion: "neutral",    text: "Silence." },
        { speaker: "Mother",     emotion: "serious",    text: "Reassigned... or demoted?" },
        { speaker: "Narrator",   emotion: "neutral",    text: "He doesn't answer." },
        { speaker: "Mei Ling",   emotion: "serious",    text: "How bad?" },
        { speaker: "Father",     emotion: "sad",        text: "One more step down and I'm out of the inner circle completely." },
        { speaker: "Narrator",   emotion: "neutral",    text: "Mother exhales sharply." },
        { speaker: "Mother",     emotion: "serious",    text: "You know what that means." },
        { speaker: "Mei Ling",   emotion: "curious",    text: "What?" },
        { speaker: "Mother",     emotion: "serious",    text: "It means your options shrink." },
        { speaker: "Mei Ling",   emotion: "neutral",    text: "Mom—" },
        { speaker: "Mother",     emotion: "serious",    text: "You're turning twenty-five." },
        { speaker: "Narrator",   emotion: "neutral",    text: "Mei Ling stiffens." },
        { speaker: "Mother",     emotion: "serious",    text: "You need stability. Protection." },
        { speaker: "Mei Ling",   emotion: "serious",    text: "You mean marriage." },
        { speaker: "Narrator",   emotion: "neutral",    text: "Her father looks away. A phone buzzes on the table. Her father glances at it — freezes." },
        { speaker: "Mei Ling",   emotion: "curious",    text: "What is it?" },
        { speaker: "Father",     emotion: "neutral",    text: "...A reminder." },
        { speaker: "Mei Ling",   emotion: "curious",    text: "For what?" },
        { speaker: "Narrator",   emotion: "neutral",    text: "He swallows." },
        { speaker: "Father",     emotion: "neutral",    text: "For the loan." },
        { speaker: "Mother",     emotion: "neutral",    text: "The one for her education?" },
        { speaker: "Narrator",   emotion: "neutral",    text: "Father nods." },
        { speaker: "Mei Ling",   emotion: "neutral",    text: "I didn't ask for that." },
        { speaker: "Father",     emotion: "neutral",    text: "You earned it." },
        { speaker: "Narrator",   emotion: "neutral",    text: "Mei Ling's breath quickens." },
        { speaker: "Mei Ling",   emotion: "serious",    text: "I came back because I had to. Not because I failed." },
        { speaker: "Mother",     emotion: "serious",    text: "And now we pay the price." },
        { speaker: "Narrator",   emotion: "neutral",    text: "Mei Ling stands abruptly." },
        { speaker: "Mei Ling",   emotion: "angry",      text: "So what, I marry whoever will take me?" },
        { speaker: "Narrator",   emotion: "neutral",    text: "Her voice cracks." },
        { speaker: "Mei Ling",   emotion: "sad",        text: "I didn't study my whole life to become a solution to debt." },
        { speaker: "Narrator",   emotion: "neutral",    text: "Her mother reaches for her." },
        { speaker: "Mother",     emotion: "sad",        text: "Mei Ling—" },
        { speaker: "Narrator",   emotion: "neutral",    text: "Mei Ling pulls away, overwhelmed." },
        { speaker: "Mei Ling",   emotion: "sad",        text: "I can't breathe." },
        { speaker: "Narrator",   emotion: "neutral",    text: "They move closer, holding her between them. Outside, the city hums — indifferent." }
    ],
    next: "chapter_4_scene"
});
